---

- set_fact:
    phpmyadmin_version: 4.9.7

- name: Copy config.inc.php (local)
  become: no
  local_action:
    module: copy
    src: config.inc.php
    dest: "{{ role_path }}/files/phpMyAdmin-{{ phpmyadmin_version }}-all-languages/"

- name: rsync phpmyadmin
  synchronize:
    src: files/phpMyAdmin-{{ phpmyadmin_version }}-all-languages/
    dest: /usr/local/share/phpmyadmin/
    owner: no
    delete: yes
    rsync_opts:
      - "--exclude=setup/"

- name: Create /etc/phpmyadmin/conf.d/
  file: state=directory path=/etc/phpmyadmin/conf.d/

- stat: path=/etc/phpmyadmin/conf.d/blowfish_secret.inc.php
  register: blowfish_secret_file

- name: Create blowfish_secret
  shell: openssl rand -base64 32 | cut -b -32
  register: blowfish_secret
  when: blowfish_secret_file.stat.exists == False

- name: Create blowfish_secret.inc.php
  copy:
    content: "<?php\n$cfg['blowfish_secret'] = '{{ blowfish_secret.stdout }}';\n?>"
    dest: /etc/phpmyadmin/conf.d/blowfish_secret.inc.php
    owner: root
    group: phpmyadmin
    mode: '0640'
  when: blowfish_secret_file.stat.exists == False

- template: src={{ item }} dest=/etc/nginx/conf.d/
  notify: Reload nginx
  with_items:
    - local-mit-phpmyadmin.include

- name: Check deprecated files
  command: find /etc/nginx/conf.d/ -name mit-phpmyadmin.include
  register: cmd_ls
  failed_when: cmd_ls.stdout
  changed_when: no

